branches:
  only:
    - master

configuration:
  - Debug
  - Release

# Modern image with VS2019/2022 compiler support
image: Visual Studio 2022

skip_commits:
  files:
    - README.md

skip_branch_with_pr: true

# -----------------------------
# Installation and Versioning
# -----------------------------
install:
  - ver
  - ps: choco install -y -r --no-progress InnoSetup
  - ps: |
      function gitVersion() {
        $env:newhash = git rev-parse HEAD
        $env:shorthash = git rev-parse --short HEAD
        $env:gitTag = (git describe --tags --abbrev=0 2>$null)

        if (-not [string]::IsNullOrEmpty($env:appveyor_repo_tag_name)) {
          # Tagged build
          $env:newVersion = $env:appveyor_repo_tag_name
          $env:appveyor_info_version = $env:appveyor_repo_tag_name
        }
        elseif (-not [string]::IsNullOrEmpty($env:gitTag)) {
          # Has previous tag
          $env:newVersion = "$env:gitTag.$env:APPVEYOR_BUILD_NUMBER"
          $env:appveyor_info_version = "$env:newVersion"
        }
        else {
          # No tags found — numeric fallback
          $env:newVersion = "1.0.$env:APPVEYOR_BUILD_NUMBER.0"
          $env:appveyor_info_version = "$($env:newVersion)-$($env:APPVEYOR_REPO_BRANCH)-$($env:shorthash)"
        }

        $env:appveyor_build_version = $env:newVersion
        appveyor UpdateBuild -Version "$env:newVersion"

        Write-Host "Commit hash: $env:newhash"
        Write-Host "AppVeyor build version: $env:appveyor_build_version"
        Write-Host "Informational version: $env:appveyor_info_version"
      }
      gitVersion

# -----------------------------
# Patch Assembly Version Info
# -----------------------------
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(appveyor_build_version)
  assembly_file_version: $(appveyor_build_version)
  assembly_informational_version: $(appveyor_info_version)

# -----------------------------
# Build Process
# -----------------------------
before_build:
  - cmd: nuget restore ScriptPlayer\ScriptPlayer.sln

build:
  parallel: true
  project: ScriptPlayer\ScriptPlayer.sln
  publish_nuget: false

# -----------------------------
# Post-Build: Package Installer
# -----------------------------
after_build:
  - ps: |
      $innoSetupPath = "C:\Program Files (x86)\Inno Setup 6"
      if (-not (Test-Path $innoSetupPath)) {
        $innoSetupPath = "C:\Program Files (x86)\Inno Setup 5"
      }
      Write-Host "Using Inno Setup path: $innoSetupPath"
      set PATH=%PATH%;"$innoSetupPath"
      iscc scriptplayer-installer.iss

  - ps: |
      $artifactPath = "installer\scriptplayer-installer.exe"
      $artifactName = "ScriptPlayer-$env:CONFIGURATION-$env:APPVEYOR_BUILD_VERSION.exe"
      if (Test-Path $artifactPath) {
        Push-AppveyorArtifact $artifactPath -FileName $artifactName
        Write-Host "✅ Uploaded artifact: $artifactName"
      } else {
        Write-Host "⚠️ Warning: Installer not found at $artifactPath"
      }
